import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('products').del();

    // Inserts seed entries
    await knex('products').insert(
        [
            {
                id: 1,
                name: 'One Life Graphic T-shirt',
                description: 'This graphic t-shirt is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
                rating: 5,
                price: 260,
                discount: 30,
                image_url: 'https://mrmockup.com/wp-content/uploads/2024/07/Free-Backside-T-Shirt-Mockup-Square-1024x1024.jpg?x26095',
                stock_quantity: 1,
                category_id: 1,
                size_id: 2,
                style_id: 1,
                type_id: 1,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 2,
                name: 'Men\'s Casual Shirt',
                description: 'A stylish and comfortable casual shirt made from 100% cotton.',
                rating: 4.5,
                price: 29.99,
                discount: 10,
                image_url: 'https://www.mockupworld.co/wp-content/uploads/dynamic/2023/06/t-shirt-shop-free-mockup-psd-536x0-c-default.jpg',
                stock_quantity: 2,
                category_id: 1,
                size_id: 2,
                style_id: 1,
                type_id: 3,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 3,
                name: 'Women\'s Winter Hoodie',
                description: 'A cozy hoodie designed for warmth and style during the colder months.',
                rating: 4.7,
                price: 49.99,
                discount: 15,
                image_url: 'https://media.istockphoto.com/id/1293292206/photo/young-beautiful-girl-in-a-white-hoodie-posing-warm-oversized-hoodie-with-an-hood-stylish.jpg?s=612x612&w=0&k=20&c=jtOCQCQieltbA-xg3GE_MNdfNsnj4i0H1qvVD837xLk=',
                stock_quantity: 3,
                category_id: 3,
                size_id: 2,
                style_id: 1,
                type_id: 4,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 4,
                name: 'Men\'s Athletic Shorts',
                description: 'Lightweight and breathable shorts perfect for workouts and casual wear.',
                rating: 4.3,
                price: 35.00,
                discount: 20,
                image_url: 'https://i5.walmartimages.com/seo/Athletic-Works-Men-s-and-Big-Men-s-Knit-Shorts-2-Pack-Sizes-S-3XL_d484b5f2-64a2-4fb4-bc74-dc28b38eb357.6a0a4b7c9f60637d0b1128b948fc78f9.jpeg?odnHeight=50px&odnWidth=50px&odnBg=FFFFFF',
                stock_quantity: 4,
                category_id: 2,
                size_id: 3,
                style_id: 4,
                type_id: 2,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 5,
                name: 'Women\'s Elegant shirts',
                description: 'A sophisticated shirts that can be dressed up or down for any occasion.',
                rating: 4.6,
                price: 45.00,
                discount: 25,
                image_url: 'https://i.pinimg.com/474x/6c/43/c3/6c43c36565556b714073e15432aa33da.jpg',
                stock_quantity: 5,
                category_id: 1,
                size_id: 2,
                style_id: 2,
                type_id: 3,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 6,
                name: 'Men\'s Denim Jacket',
                description: 'A classic denim jacket that never goes out of style, perfect for layering.',
                rating: 4.4,
                price: 75.00,
                discount: 10,
                image_url: 'https://i5.walmartimages.com/seo/Men-s-The-Trucker-Jacket_e956615c-5f71-4f27-950f-3b3460ed05e3_1.822afa92300b 8dea0395359b9404f2e6.jpeg',
                stock_quantity: 6,
                category_id: 1,
                size_id: 2,
                style_id: 1,
                type_id: 1,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 7,
                name: 'Women\'s pants',
                description: 'A flowypant  dress that is perfect for summer outings and beach days.',
                rating: 4.8,
                price: 60.00,
                discount: 15,
                image_url: 'https://i.pinimg.com/736x/74/0d/5d/740d5d0830b10f9027ce627922bb17a6.jpg',
                stock_quantity: 7,
                category_id: 2,
                size_id: 2,
                style_id: 1,
                type_id: 4,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 8,
                name: 'Men\'s Formal Shirt',
                description: 'A crisp formal shirt perfect for special occasions and business meetings.',
                rating: 4.9,
                price: 80.00,
                discount: 20,
                image_url: 'https://i.pinimg.com/474x/c7/3c/1d/c73c1d88e0ff11cb515aa6c64467dcfb.jpg',
                stock_quantity: 8,
                category_id: 3,
                size_id: 2,
                style_id: 2,
                type_id: 3,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 9,
                name: 'Women\'s Yoga Pants',
                description: 'Stretchy yoga pants designed for comfort and flexibility during workouts.',
                rating: 4.5,
                price: 40.00,
                discount: 25,
                image_url: 'https://img.freepik.com/premium-photo/woman-white-tank-top-is-standing-gym_1216215-3758.jpg?semt=ais_hybrid',
                stock_quantity: 5,
                category_id: 2,
                size_id: 2,
                style_id: 4,
                type_id: 2,
                created_by: 'admin',
                updated_by: 'admin',
            },
            {
                id: 10,
                name: 'Men\'s Leather Belt',
                description: 'A high-quality leather belt that adds a touch of sophistication to any outfit.',
                rating: 4.7,
                price: 50.00,
                discount: 15,
                image_url: 'https://thumbs.dreamstime.com/b/mens-belts-especially-genuine-leather-46767173.jpg',
                stock_quantity: 6,
                category_id: 1,
                size_id: 2,
                style_id: 1,
                type_id: 1,
                created_by: 'admin',
                updated_by: 'admin',
            },
        ],
    );
}

